config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:index, :create, :destroy]
  get '/login', to: "session#new"

  # if needed for comment #
  post '/categories/:id/articles/:id', to: "comments#create", as: 'create_comment'
  delete '/articles/:id/comments/:id', to: "comments#destroy", as: 'delete_comment'
  #

  #for test#
  get '/test', to: "static#test"
  ##

  namespace :admin do
    resources :articles
    # destroy 'articles/:id', to: "articles#destroy", as: "delete_article"
    root to: "articles#index"
  end

  resources :categories, only: [:show, :index] do
    resources :articles
  end

  root to: "static#welcome"

  get '/', to: "static#welcome"

end

app/models/admin.rb
class Admin < ApplicationRecord
    # attr_reader :email, :password
    has_secure_password

    validates_uniqueness_of :email
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :category
    has_many :comments
    has_rich_text :content

    validates :content, presence: true
    validates :title, presence: true
    validates :category_id, presence: true

    def to_param
        "#{id}-#{title.parameterize}"
    end

end

app/models/category.rb
class Category < ApplicationRecord
    has_many :articles

    def to_param
        "#{id}-#{name.parameterize}"
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article

    validates :text, presence: true


end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  # before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  layout 'base', :only => [:new]
  layout 'admin'

  # GET /articles
  # GET /articles.json
  def index
    if params[:search]
      #MAKE SEARCH WITH SQL COMMAND ## W H E R E ##
      @articles = Article.all.select{|art| art.title.downcase.include?(params[:search].downcase)}
    else
      @articles = Article.all
    end

    if @articles == []
      @s = true
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    # byebug
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new(title: "new-article")
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.create(title: params[:title], content: params[:content], category_id: params[:category_id])
    # byebug
    redirect_to "/admin/articles/#{@article.to_param}"
  end

  def update
    @article = Article.find(params[:id])
    # byebug
    if @article.update!(article_params)
        flash[:success] = "Edits Has Been Saved!"
        # @article.update(article_params)
        redirect_to admin_article_path(@article)
    else
        flash[:fail] = "Edits Has Not Been Saved! Make Sure You Didn't Leave Blank Section!"
        redirect_to edit_admin_article_path(@article)
    end
  end

  def destroy
    # byebug
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to "/admin/articles"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params[:article] = {}
      params[:article][:title] = params[:title]
      params[:article][:content] = params[:content]
      params[:article][:category_id] = params[:category_id]
      params.require(:article).permit(:title, :content, :category_id)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    private
    def current_admin
        @current_admin ||= Admin.find(session[:admin_id]) if session[:admin_id]
    end

    def authorize
        redirect_to '/login' if current_admin.nil?
    end
    helper_method :current_admin
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    # respond_to :html, :js, only: [:show]

    layout "show_lo", :only => [:show]
    # GET /articles
    # GET /articles.json
    def index
      @category = Category.find(params[:category_id])
      # byebug
      if params[:search]
        #MAKE SEARCH WITH SQL COMMAND ## W H E R E ##
        @articles = Article.all.select{|art| art.title.downcase.include?(params[:search].downcase)}
        if @articles == []
          @s = true
        else
          @articles == []
        end
      else
        @articles = Article.all.select{|art| art.category_id.to_i == @category.id}
        if @articles == []
          @t = true
        else

        end
      end

    end

    def show
      @related_articles1 = []
      @article = Article.find(params[:id])
      @comment = Comment.new
      @article_title_words = @article.title.downcase.split(' ')

      @related_articles = Article.all.select{|art| (art.title.downcase.split(' ') & @article_title_words).any? }
      @related_articles.delete_if{ |ra| ra == @article}
      # byebug
      if @related_articles.count > 3
        3.times do
          x = rand(0...@related_articles.size)
          @related_articles1 << @related_articles[x]
          @related_articles[x].delete
        end
      else
        @related_articles1 = @related_articles.uniq
                respond_to do |format|
            format.html
            format.json
          end
      end
      # byebug
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_article
        @article = Article.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def article_params
        params.fetch(:article, {})
      end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # validates :created_at, :presence => true

    def create
        # byebug
        @article = Article.find(params[:id])
        @comment = Comment.new(text: params[:comment][:text], article_id: @article.id)

        if @comment.valid?
            @comment.save
            flash[:notice] = "Comment Added!"
            # redirect_to category_article_path(@article)
        else
            flash[:notice] = "Comment Should Not Be Blank!"
            # redirect_to category_article_path(@article)
        end

        respond_to do |format|
            format.json { render json: @comment }
            format.html { render layout => false }
            format.js
          end

    end

    def destroy
        # byebug
        Comment.delete(params[:id])
        redirect_to admin_article_path(Article.find(params[:article_id]))
    end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end

  def create
    # byebug
    admin = Admin.find_by_email(params[:email])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to "/admin/articles"
    else
      flash[:notice] = "Email or Password is Incorrect!"
      redirect_to '/login'
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to "/"
  end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    layout 'test1', only: [:test]
    # layout 'base'
    def welcome
        if params[:query]
            redirect_to "/categories/1-politics/articles/?query=#{params[:query]}"
        end
    end

    def test
        @articles = Article.all
    end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admin/articles/index.html.erb
<%= content_for :title do %>
    <title>Articles</title>
    <% end %>
  
    <%= content_for :body do %>
    <% if @s %>
    <br>
    <br>
    <br>
       <h2> Sorry, we couldn't find anything for that search... Try another words! </h2>    
    <% end %>
  
        <% @articles.each do |art| %>
          <h3><%= art.title %></h3>
          <h5><%= Category.find(art.category_id).name%></h5>
          <h6><%= art.created_at.strftime("%b, %-d %Y, %H:%M") %></h6>
          <p class="border border-warning"><%= art.content %></p>

          <%= link_to 'Show This Article', admin_article_path(art) %> <br>
          <%= link_to 'Edit This Article', edit_admin_article_path(art) %> <br>
          <%= link_to 'Delete This Article', admin_article_path(art), method: :delete %>
          <br>
          <br>
          <br>
        <% end %>
        <br>            
    <% end %>

app/views/admin/articles/new.html.erb
<%= content_for :title do %>
    <title>Create An Article!</title>
<% end %>

<%= content_for :body do %>
<h3>Create a New Article:</h3>
<h6>Current Day: <%= Time.now.strftime("%b %Y") %> </h6>
<br>
    <%= form_for @article, url: admin_articles_path do |f| %>
     <div class="form-group">
            <label for="title">Please Enter a Title:</label>
            <input type="text" class="form-control" id="title" name="title" aria-describedby="muted_desc" placeholder="New Title...">
            <small id="muted_desc" class="form-text text-muted">You can change whenever you want...</small>
        </div>
        <div class="form-group">
                <select class="custom-select" name="category_id">
                        <option selected> Please Choose a Category </option>
                        <option value="1">Politics</option>
                        <option value="2">Economy</option>
                        <option value="3">Food</option>
                        <option value="4">Magazine</option>
                </select>
                <!-- <div class="invalid-feedback">Example invalid custom select feedback</div> -->
        </div>
        <br>
        <div class="form-group">
            <label for="content">Article Content:</label>
            <input id="x" type="hidden" name="content" class="form-control">
            <trix-editor input="x"></trix-editor>
        </div>  
        
        <button type="submit" class="btn btn-warning btn-sm">Create Your Article!</button>
        <br>
        <br>
    <% end %>

<% end %>

app/views/admin/articles/show.html.erb
<%= content_for :title do %>
    <title><%= @article.title %></title>
    <% end %>

    <%= content_for :body do %>
          <% if flash[:success] %>
              <div class="alert alert-success" role="alert"> <%= flash[:success] %> </div>
          <% end %>
          <div>
          <h3 class="d-flex justify-content-center"><%= @article.title %></h3>
          <h7 style="text-align:left;float:left;"><%= Category.find(@article.category_id).name%></h7>
          <h7 style="text-align:right;float:right;"><%= @article.created_at.strftime("%-d %b %Y") %></h7>
          </div>
          <br>
          <div>
          <p class="border border-warning"><%= @article.content %></p>
          </div>
          <br>

          <h4>Comments</h4>
            <% if flash[:notice] == "Comment Added!" %>
                <div class="alert alert-success" role="alert"> <%= flash[:notice] %> </div>
              <% elsif  flash[:notice] == "Comment Couldn't Added Try Again..." %>
                <div class="alert alert-danger" role="alert"> <%= flash[:notice] %> </div>
            <% end %>
            <ul class="list-group">
              <% @article.comments.each do |comment| %>
              <div>
            <li class="list-group-item d-flex justify-content-between align-items-center">
             <%= comment.text %>

             <%= form_tag delete_comment_path(@article, comment), method: :delete do %>
              <button type="submit" value=<%= "#{@article.to_param}"%> name="article_id" class="badge badge-danger">X</button>
             <% end %>

            </div>
            </li>
          <% end %>
            </ul>
          <br>

          <%= link_to 'Back To List', admin_articles_path %><br>
          <%= link_to 'Edit This Article', edit_admin_article_path(@article) %> <br>
          <%= link_to 'Delete This Article', admin_article_path(@article), method: :delete %>
          <br>
          <br>
    <% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/show.html.erb
<%= content_for :title do %>
    <title><%= @article.title %></title>
    <% end %>

    <%= content_for :body do %>
          <div>
          <h3 class="d-flex justify-content-center"><%= @article.title %></h3>
          <h7 style="text-align:left;float:left;"><%= Category.find(@article.category_id).name%></h7>
          <h7 style="text-align:right;float:right;"><%= @article.created_at.strftime("%-d %b %Y") %></h7>
          </div>
          <br>
          <p class="border border-warning"><%= @article.content %></p>

          <br>
          <% if @related_articles1 != [] %>

          <h4>Related Articles</h4>
          <ul class="list-group list-group-horizontal-md ">

            <% @related_articles1.each do |ra| %>
              <li class="list-group-item col-4" style="text-align:center;">
                  <div class="text-truncate">
                  <%= link_to ra.title, category_article_path(ra.category.to_param, ra), target: "blank_" %>
                  </div>
              </li>
            <% end %>
           </ul>
           <% else %>
            <div>
              <h5 align="center" class="text-dark" > We couldn't find any related articles... </h5>
            </div>
           <% end %>
           <br>
           <div>
            <h4>Comments</h4>
              <ul class="list-group">
                <% @article.comments.each do |comment| %>
                <div id="asd">
                  <li class="list-group-item d-flex justify-content-between align-items-center">
                   <%= comment.text %>
                   <span class="badge badge-warning badge-pill"> <%= comment.created_at.strftime("%b %-d %Y, %H:%M") %> </span>
                  </li>
                </div>
              <% end %>
              </ul>
          </div>
          <br>
            <h5>Add Comment</h5>
          <div id="comment-notice" >
              <!-- AJAX FLASH NOTICE! => CHECK app/views/comments/create.js.erb -->
          </div>
              <%= form_with model: @comment, url: create_comment_path, class: "create_comment", remote: true do |f| %>
              <%= f.text_field :text, class: "form-control", id: "comment-text" %> <br>
              <%= f.submit 'Send', class: "btn-sm btn-outline-warning float-right" %><br><br>

              <% end %>
          <br>
          <%= link_to 'Back', "/categories/#{Category.find(@article.category_id).to_param}/articles" %>
          <br>
    <% end %>

app/views/layouts/admin.html.erb
<!doctype html>
<html lang="en">
  <head>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="stylesheet" type="text/css" href="trix.css">
  <script type="text/javascript" src="trix.js"></script>

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= yield :title %>
  </head>
  <body style="padding-bottom: 75px;">
      <nav class="navbar navbar-expand-xl navbar-light bg-light">
          <a class="navbar-brand" href="/">
              <img src="/images/myblog.png" width="30" height="30" href="/admin/articles"> MyBlog </a>

          <ul class="navbar-nav ">
            <a class="nav-link disabled"> Admin Panel </a>
            <a class="nav-link" href="/admin/articles"> All Articles </a>
            <a class="nav-link" href="/admin/articles/new"> Create An Article </a>
        </ul>

          <form class="form-inline" style = "position:relative; left: 675px; top:2px;">
            <input class="form-control mr-sm-2 btn-outline-warning" type="search" placeholder="Search Articles..." aria-label="Search" name="search">
            <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
          </form>
          
      </nav>

    
      <nav class="navbar fixed-bottom  navbar-expand-xl navbar-light bg-light">
      <ul class="navbar-nav d-flex justify-content-end" >
      <% if current_admin %>
        <li class="nav-item">
          <a class="nav-link" href="/admin/articles">Logged in as, <%= current_admin.email %>.</a>
        </li>
        <%= form_tag session_path(session), method: :delete, style: "position:relative; left: 1000px; top:2px;" do %>
            <li class="nav-item">
                <button type="submit" class="btn btn-warning btn-sm ">Log Out</button>      
            </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/login"> Log Into Admin Panel </a>
        </li>
      <%end %>
      </ul>
      </nav>
  
      <div class="container  pt-5">
          <%= yield :body %>
      </div>
      
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="shortcut icon" href="favicon.png" type="image/png">
  <link rel="icon" href="favicon.png" type="image/png">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= yield :title %>
  </head>
  <body class ="container-fluid" style="padding-bottom: 75px;">
      <nav class="navbar navbar-expand-xl navbar-light bg-light">
          <a class="navbar-brand" href="/">
              <img src="/images/myblog.png" width="30" height="30" href="/"> MyBlog </a>

          <ul class="navbar-nav ">
            <a class="nav-link" href="/categories/1-politics/articles">
               <img class="d-inline-block align-top" src="/images/picon.png" width="25" height="25"> Politics </a>


            <a class="nav-link" href="/categories/2-economy/articles">
               <img class="float-up" src="/images/eicon.png" width="25" height="25"> Economy </a>


            <a class="nav-link" href="/categories/3-food/articles">
               <img class="float-up" src="/images/foodicon.png" width="25" height="25"> Food </a>

            <a class="nav-link" href="/categories/4-magazine/articles">
               <img class="float-up" src="/images/micon.png" width="25" height="25"> Magazine </a>
          </ul>

          <form class="form-inline" style = "position:relative; left:600px; top:2px;">
            <input class="form-control mr-sm-2 btn-outline-warning" type="search" placeholder="Search Articles..." aria-label="Search" name="search">
            <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
          </form>

      </nav>


      <nav class="navbar fixed-bottom  navbar-expand-xl navbar-light bg-light">
      <ul class="navbar-nav d-flex justify-content-end" >
      <% if current_admin %>
        <li class="nav-item">
          <a class="nav-link" href="/admin/articles">Logged in as, <%= Admin.find(session[:admin_id]).email %>.</a>
        </li>
        <%= form_tag session_path(session), method: :delete, style: "position:relative; left: 1000px; top:2px;" do %>
            <li class="nav-item">
                <button type="submit" class="btn btn-warning btn-sm ">Log Out</button>
            </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/login">Admin Panel</a>
        </li>
      <%end %>
      </ul>
      </nav>

      <div class="container  pt-5">
          <%= yield :body %>
      </div>
        <div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        </div>
  </body>
</html>

app/views/layouts/base.html.erb
<!doctype html>
<html lang="en">
  <head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!-- <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> -->
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <link rel="shortcut icon" href="favicon.png" type="image/png">
  <link rel="icon" href="favicon.png" type="image/png">

  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= yield :title %>
  </head>
  <body class ="container-fluid" style="padding-bottom: 75px;">
      <nav class="navbar navbar-expand-xl navbar-light bg-light">
          <a class="navbar-brand" href="/">
              <img src="/images/myblog.png" width="30" height="30" href="/"> MyBlog </a>

          <ul class="navbar-nav ">
            <a class="nav-link" href="/categories/1-politics/articles">
               <img class="d-inline-block align-top" src="/images/picon.png" width="25" height="25"> Politics </a>
          
         
            <a class="nav-link" href="/categories/2-economy/articles">
               <img class="float-up" src="/images/eicon.png" width="25" height="25"> Economy </a>
       
      
            <a class="nav-link" href="/categories/3-food/articles">
               <img class="float-up" src="/images/foodicon.png" width="25" height="25"> Food </a>
       
            <a class="nav-link" href="/categories/4-magazine/articles">
               <img class="float-up" src="/images/micon.png" width="25" height="25"> Magazine </a>
          </ul>
          
      </nav>


      <nav class="navbar fixed-bottom  navbar-expand-xl navbar-light bg-light">
      <ul class="navbar-nav d-flex justify-content-end" >
      <% if current_admin %>
        <li class="nav-item">
          <a class="nav-link" href="/admin/articles">Logged in as, <%= Admin.find(session[:admin_id]).email %>.</a>
        </li>
        <%= form_tag session_path(session), method: :delete, style: "position:relative; left: 1000px; top:2px;" do %>
            <li class="nav-item">
                <button type="submit" class="btn btn-warning btn-sm ">Log Out</button>      
            </li>
        <% end %>
      <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/login">Admin Panel</a>
        </li>
      <%end %>
      </ul>
      </nav>
  
      <div class="container  pt-5">
          <%= yield :body %>
      </div>
      
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/session/new.html.erb
<%= content_for :title do %>
    <title>Admin Login</title>
<% end %>

<%= content_for :body do %>
    <% if flash[:notice] %>
        <div class="alert alert-danger" role="alert"> <%= flash[:notice] %> </div>
    <% end %>

    <%= form_tag session_index_path do %>
    <div class="form-group">
        <label for="new_list_name">E-mail:</label>
        <input type="text" class="form-control" id="new_list_name" name="email" placeholder="example@example.com">
        <br>
        <label for="new_list_name1">Password:</label>
        <input type="password" class="form-control" id="new_list_name1" name="password" placeholder="123456">
        <br>
        <button type="submit" class="btn btn-warning btn-sm ">Log In as Admin</button>
    <% end %>
<% end %>